site_name: BNCC Classifier
theme:
  name: material
markdown_extensions:
  - meta
  - attr_list
  - md_in_html
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
plugins:
  - search
  - mermaid2
nav:
  - Home: "index.md"
  - Estrutura do Projeto: "estrutura-do-projeto.md"
  - Desenho da solução: "part-2.md"
  - Dados e Solução: "part-3.md"
  - Análise Exploratória: "part-4.md"
  - API (MVP): "part-5.md"
